name: Setup with full cache
description: Common setup with full cache

inputs:
  elixir-version:
    description: Elixir version
    required: true
  otp-version:
    description: OTP version
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Elixir/OTP
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}

    - name: Cache deps
      uses: actions/cache@v4
      with:
        path: deps
        key: deps-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: deps-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: _build
        key: build-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: build-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-
